# Generated by Django 5.0.3 on 2024-10-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/group/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile/'),
        ),
    ]
