# Generated by Django 5.0.3 on 2024-10-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_chat_chat_image_alter_user_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('community_image', models.ImageField(blank=True, null=True, upload_to='static/channel/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='home.community')),
            ],
        ),
    ]
