# Generated by Django 5.0.3 on 2024-10-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='community_image',
            new_name='channel_image',
        ),
    ]
