# Generated by Django 5.0.3 on 2024-10-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_community_image_channel_channel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='channel_id',
            new_name='chat_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='community',
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.channel'),
        ),
    ]
